
[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 1.0
dynamic_padding = true

[window.padding]
x = 2
y = 3

[mouse]
hide_when_typing = true

[terminal]
shell = "fish"

[general]
live_config_reload = true
import = ["/home/Ayobami/.config/alacritty/rose-pine.toml", "/home/Ayobami/.config/alacritty/fonts.toml"]
