import = ["/home/Ayobami/.config/alacritty/oxocarbon-dark.toml", "/home/Ayobami/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 1.0
dynamic_padding = true

[window.padding]
x = 1
y = 1

[mouse]
hide_when_typing = true
